import {test} from 'node:test';import assert from 'node:assert/strict';import {execFile} from 'node:child_process';import {spawn} from 'node:child_process';
test('MCP exposes speech plus accurate clock and timestamped native history tools',async()=>{
 const p=spawn(process.execPath,['src/cli.js','mcp']);let out='';p.stdout.on('data',x=>out+=x);p.stdin.end([JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'}),JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'current_time',arguments:{}}})].join('\n')+'\n');await new Promise((r,j)=>{p.on('close',r);p.on('error',j)});const results=out.trim().split('\n').map(JSON.parse);assert.deepEqual(results[0].result.tools.map(x=>x.name),['speak','current_time','session_history']);const now=JSON.parse(results[1].result.content[0].text);assert.ok(Math.abs(Date.now()-Date.parse(now.utc))<5000);assert.ok(now.timezone);assert.ok(now.local);
});
test('CLI stdin and MCP speech use the same browser-free endpoint with literal text',async()=>{
 const {default:http}=await import('node:http');const {mkdtemp,writeFile,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const dir=await mkdtemp(join(tmpdir(),'af-cli-'));await writeFile(join(dir,'auth.json'),JSON.stringify('fixture-token'));const requests=[];
 const server=http.createServer(async(req,res)=>{let body='';for await(const part of req)body+=part;requests.push({path:req.url,token:req.headers['x-agentflow-token'],text:JSON.parse(body).text});res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true}))});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 async function run(args,input){const p=spawn(process.execPath,['src/cli.js',...args],{env:{...process.env,AGENTFLOW_HOME:dir,AGENTFLOW_URL:'http://127.0.0.1:'+server.address().port}});let out='';p.stdout.on('data',x=>out+=x);p.stdin.end(input);const code=await new Promise(r=>p.on('close',r));return {out,code}}
 try{const text='Literal $HOME, `code`, $(command), and Unicode: café.\n';assert.equal((await run(['speak'],text)).code,0);const reply=await run(['mcp'],JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'speak',arguments:{text}}})+'\n');assert.equal(reply.code,0);assert.match(JSON.parse(reply.out).result.content[0].text,/played/);assert.deepEqual(requests,[{path:'/api/speak',token:'fixture-token',text},{path:'/api/speak',token:'fixture-token',text}]);}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true})}
});
test('MCP speech execution failures are tool errors, never false playback success',async()=>{
 const p=spawn(process.execPath,['src/cli.js','mcp'],{env:{...process.env,AGENTFLOW_HOME:'/nonexistent-agentflow-test-home'}});let out='';p.stdout.on('data',x=>out+=x);p.stdin.end(JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'speak',arguments:{text:'hello'}}})+'\n');await new Promise(r=>p.on('close',r));const response=JSON.parse(out);assert.equal(response.result?.isError,true);assert.match(response.result.content[0].text,/Start Agentflow/);
});
