interface Elements {
  new: HTMLButtonElement;
  search: HTMLInputElement;
  refresh: HTMLButtonElement;
  sessions: HTMLElement;
  settingsButton: HTMLButtonElement;
  agentLabel: HTMLElement;
  sessionTitle: HTMLElement;
  project: HTMLElement;
  liveConnect: HTMLButtonElement;
  transcriptToggle: HTMLButtonElement;
  notice: HTMLElement;
  sessionBadge: HTMLElement;
  orb: HTMLElement;
  state: HTMLElement;
  hint: HTMLElement;
  handsfree: HTMLInputElement;
  talk: HTMLButtonElement;
  interrupt: HTMLButtonElement;
  end: HTMLButtonElement;
  sttLabel: HTMLElement;
  ttsLabel: HTMLElement;
  testVoice: HTMLButtonElement;
  approval: HTMLElement;
  approvalText: HTMLElement;
  allow: HTMLButtonElement;
  deny: HTMLButtonElement;
  nativePanel: HTMLElement;
  hideNative: HTMLButtonElement;
  nativeTerminal: HTMLElement;
  transcript: HTMLElement;
  replay: HTMLButtonElement;
  messages: HTMLElement;
  composer: HTMLFormElement;
  message: HTMLInputElement;
  sessionId: HTMLElement;
  copyResume: HTMLButtonElement;
  settings: HTMLDialogElement;
  settingsForm: HTMLFormElement;
  closeSettings: HTMLButtonElement;
  sttProvider: HTMLSelectElement;
  sttModel: HTMLInputElement;
  ttsProvider: HTMLSelectElement;
  deepgramVoiceField: HTMLElement;
  deepgramVoice: HTMLSelectElement;
  deepgramVoiceHelp: HTMLElement;
  previewVoice: HTMLButtonElement;
  ttsModelField: HTMLElement;
  ttsModel: HTMLInputElement;
  ttsVoiceField: HTMLElement;
  ttsVoice: HTMLInputElement;
  ttsSpeed: HTMLSelectElement;
  routerUrl: HTMLInputElement;
  keyRows: HTMLElement;
  settingsNotice: HTMLElement;
  routerModels: HTMLButtonElement;
  newDialog: HTMLDialogElement;
  newForm: HTMLFormElement;
  closeNew: HTMLButtonElement;
  newAgent: HTMLSelectElement;
  newCwd: HTMLInputElement;
}
export function element<K extends keyof Elements>(id: K): Elements[K] {
  const el = document.getElementById(id);
  if (!el) throw Error("Missing element: " + id);
  return el as Elements[K];
}
